project_id = "zldeaozqxjwvzgrblyrh"

[functions.get-queue-users]
verify_jwt = false

[functions.send-whatsapp-message]
verify_jwt = false

[functions.message-sender]
verify_jwt = false

[functions.n8n-send-message]
verify_jwt = false

[functions.n8n-media-processor]
verify_jwt = false

[functions.evolution-webhook-v2]
verify_jwt = false

[functions.process-profile-image]
verify_jwt = false

[functions.test-send-msg]
verify_jwt = false
