project_id = "zldeaozqxjwvzgrblyrh"

[functions.send-whatsapp-message]
verify_jwt = false

[functions.message-sender]
verify_jwt = false

[functions.n8n-send-message]
verify_jwt = false

[functions.n8n-media-processor]
verify_jwt = false

[functions.evolution-webhook-v2]
verify_jwt = false
